### ISSUE TITLE
Recent name chat :)

### ISSUE THREAD

**Issue by crazzyt9** [B4T3S/DiscordDarkNeon#15]
So ahh yea anyway you can update the theme on https://betterdiscord.app to reflect your current name so the theme isn't broken for folks :) 

None working
`@import url('https://commandcrafterhd.github.io/DiscordDarkNeon/mainRewrite.css');`

`@import url('https://commandcrafterhd.github.io/DiscordDarkNeon/css/hideUsers.css');`

Working
`@import url('https://b4t3s.github.io/DiscordDarkNeon/mainRewrite.css');`

`@import url('https://b4t3s.github.io/DiscordDarkNeon/css/hideUsers.css');`

This also obviously effects the Fallout 4 Terminal theme

**Comment by B4T3S** [comment]
Yep, I'm waiting for support from the Betterdiscord folks tho, because they have to update the URL for me before I can push an update to the actual files ^^
